### ISSUE TITLE
Improve CVE report with JIRA information

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#1]
- [ ] Add the hyperlink of the ENTSBT ticket link to a CVE/Bugzilla 
- [ ] Using the link provided in the report (or list of JIRA/Bugzilla records) to add the status, snowdrop release
- [x] Enhance the code to support [OAuth](https://community.atlassian.com/t5/Questions/Access-to-JIRA-ressource-using-com-atlassian-jira-jira-rest-java/qaq-p/705465)

**Comment by cmoulliard** [comment]
According to our colleagues, it is not needed to change the code to use `OAuth2`.

Example: https://github.com/jboss-set/aphrodite/blob/master/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java#L108-L120

**Comment by metacosm** [comment]
Is this ticket still needed?

**Comment by metacosm** [comment]
> Is this ticket still needed?

ping @cmoulliard @jacobdotcosta

**Comment by cmoulliard** [comment]
No if a weekly CVE report is generated and that we could use this report to track the CVEs : new, pending, closed, if they will be part of ENTSBT release, ...

**Comment by metacosm** [comment]
> No if a weekly CVE report is generated and that we could use this report to track the CVEs : new, pending, closed, if they will be part of ENTSBT release, ...

There's a filter that you can subscribe to that lets you know which CVEs are pending. That said, handling CVEs is not going to magically be done if no one takes care of them and that should be a team responsibility: it should probably be done during the weekly call.

**Comment by cmoulliard** [comment]
> it should probably be done during the weekly call.

I agree at the condition that the information is updated for the weekly call within the Google doc ....

**Comment by metacosm** [comment]
> > it should probably be done during the weekly call.
> 
> I agree at the condition that the information is updated for the weekly call within the Google doc ....

Why? You can get that information in JIRA. Why should it be duplicated in a different doc?

**Comment by cmoulliard** [comment]
If this filter view is up to date - https://issues.redhat.com/issues/?filter=12347058., then we will have an overview about the situation. Nevertheless, it will be difficult to figure out if `NEW` tickets have been created since last week (= to avoid that we review every week the same CVEs) OR If a decision is needed for the other tickets

**Comment by metacosm** [comment]
Reviewed tickets should not be left as NEW but changed to another status. Another way to also differentiate would be to always set a fixVersion for all tickets that have been reviewed.

**Comment by cmoulliard** [comment]
Can you add then this point to the weekly call to take a decision around CVE status creation and fixVersion assigned please ?
