### ISSUE TITLE
New command to initialize a new release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#111]
This command (e.g. ìnit-release`) should:

 - [ ]  create the release-<version>.yml file from the template requesting as parameters the values to be applied to the template
   - [ ]  SpringBoot version
   - [x] Release date
   - [x] EOL date
   - [x] Previous version
- [ ] Create new branch on CPaaS for the release
- [ ] Create new branch on BuildConfigurations project for the release

**Comment by metacosm** [comment]
Shouldn't that be done by `start-release`?

**Comment by jacobdotcosta** [comment]
I think you're right as nothing here is required by the `align bom with upstream` action. I'll take a look at it better.

**Comment by jacobdotcosta** [comment]
This issue is canceled as the tasks proposed don't fit in this step.
