### ISSUE TITLE
Rename project to issues-manager

### ISSUE THREAD

**Issue by metacosm** [snowdrop/issues-manager#16]
The name is more generic. What do you think, @cmoulliard?

**Comment by cmoulliard** [comment]
LGTM. So go ahead to rename it

**Comment by cmoulliard** [comment]
Dont forget too to add to the README file the instructions to also Get, Get a bulk of issue, Delete or Create an issue ;-)

**Comment by metacosm** [comment]
> Dont forget too to add to the README file the instructions to also Get, Get a bulk of issue, Delete or Create an issue ;-)

The documentation will be updated later.
