### ISSUE TITLE
Investigate using a generic / bot account to trigger issues-manager

### ISSUE THREAD

**Issue by metacosm** [snowdrop/issues-manager#31]
The account should be set up in such a way that it has appropriate permissions on jira and so that all engineering members of the team could get notified of answers to create jira tickets.

**Comment by jacobdotcosta** [comment]
We have a JIRA bot account that is already being used in the snowdrop-bot project. 

Regarding the notifications, what if we add each of us as watcher to all the JIRA Issue? The snowdrop-bot project already manages conceptually a list of associate IDs from JIRA. The JIRA API should support adding watchers to an Issue (https://community.atlassian.com/t5/Answers-Developer-Questions/Please-Help-Got-error-400-when-trying-to-add-watcher-using-REST/qaq-p/567259).

WDYT @metacosm ?
