### ISSUE TITLE
Populate a github issue ticket with status update about a release or CVE

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/issues-manager#64]
## Feature request

Populate a github issue ticket where the description of the ticket will contain a status report about a release like also for the the CVE

The description will contain 2 tables where one is about the `releases` and the second about `CVE`

The release table will include for each release the list of the linked and related tasks, their status and if some tasks are still older than 1month and where status is still new, work in process, then a small red box will be displayed in front of the line to warn the team and product owner

The CVE will be similar as the release table but will also include the `labels` able to decorate, enhance the description of the progress did around the issue

**Comment by metacosm** [comment]
We should only do that if we create the ticket to a private github org and make sure that only allowed people are part of the org (i.e. only people with security privileges).

**Comment by metacosm** [comment]
I'm more in favor of running the client locally rather than risking exposing data this way. Obviously, it's also much easier to implement that way 😁

**Comment by jacobdotcosta** [comment]
We already have a private repository for the reports, we could create a new report with this information.

**Comment by jacobdotcosta** [comment]
Closed with PR #76
