### ISSUE TITLE
Provide a label to explain the status of the issue

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/issues-manager#73]
## Problem

The following CVEs report - https://github.com/snowdrop/reports/issues/119 dont mention for by example the issue `ENTSB-386` that a comment has ben added within the JIRA ticket and that we must wait about a new release of keycloak.

## Todo

Ideally for tickets such as `ENTSB-386`, a comment = label should be used within the report to mention `waitingNewReleaseKeycloak` as until now we have no idea about the status of the CVE, if we must wait, should contact somebody, take a decision, ...

**Comment by metacosm** [comment]
I don't think that a label is needed but there should definitely be a blocker that explains the status of the issue.

**Comment by metacosm** [comment]
Actually, this isn't a bug. After investigation, it works as "expected": you only see what you're allowed to see so if the user who runs the command doesn't have access to the children issues, then `issues-manager` doesn't see them either and cannot report the status incorrectly. There's unfortunately nothing that can be done there apart from running the tool with a user that has sufficient privileges.

**Comment by cmoulliard** [comment]
> if the user who runs the command doesn't have access to the children issues, then `issues-manager` doesn't see them either and cannot report the status incorrectly.

As the tool is launched by the bot afaik, how can we then fix this access issue ?

**Comment by metacosm** [comment]
> > if the user who runs the command doesn't have access to the children issues, then `issues-manager` doesn't see them either and cannot report the status incorrectly.
> 
> As the tool is launched by the bot afaik, how can we then fix this access issue ?

The answer is contained in your question: give the bot access… 😁

**Comment by cmoulliard** [comment]
> The answer is contained in your question: give the bot access…

Then someone should lead this action item. Is there a ticket opened to give access to the service account of the bot ?

**Comment by metacosm** [comment]
> > The answer is contained in your question: give the bot access…
> 
> Then someone should lead this action item. Is there a ticket opened to give access to the service account of the bot ?

I don't think that's going to be that simple… and actually, the report is probably not generated using the bot's account because the bot doesn't have access to CVEs.
