### ISSUE TITLE
Add reference to the embargoed issues

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#78]
The EMBARGOED prefix is being removed from the subject of the issue. Is this a side effect of removing the CVE number or is it made on purpose?

**Comment by metacosm** [comment]
> The EMBARGOED prefix is being removed from the subject of the issue. Is this a side effect of removing the CVE number or is it made on purpose?

It's a side effect of removing the CVE number.

**Comment by jacobdotcosta** [comment]
I'll add it back then, only that word.
