### ISSUE TITLE
Close previous versions of the report for the same release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/issues-manager#79]
The issue title could have the generation date to help identifying how old is the information.

**Comment by metacosm** [comment]
While interesting, it is somewhat redundant since you could also just look at the date the issue was created… 😄 
Also, as mentioned elsewhere, we should probably close the previous report issues when generating new ones.

**Comment by jacobdotcosta** [comment]
The scope will be then to close previous versions of the report, for the same release. This will be detected by the issue title.
